// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Seed command for development using TypeScript seed script.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI (migrations) uses this URL.
    // DIRECT_URL (non-pooled) is preferred for migrations;
    // DATABASE_URL (pooled) is used as fallback.
    // Both require a running Postgres instance.
    url: process.env.DIRECT_URL ?? process.env.DATABASE_URL ?? "",
  },
});
